// <auto-generated />
namespace LaraAbdallah_Homework3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "202005131331298_AddDatetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
